import java.util.Objects;

public class Vehicle {
    private String make;
    private String model;
    private double emissionsPerMile;
    private Person owner;
    private String streetLegal;

    public Vehicle(Vehicle copyVehicle){
//        this.make = copyVehicle.getMake();
//        this.model = model;
//        this.emissionsPerMile = emissionsPerMile;
        //copy all of the copyVehicle members into the current one
//        this(copyVehicle.getMake(),...)
    }

    /**
     * constructor
     * @param make
     * @param model
     * @param emissionsPerMile
     */
    public Vehicle(String make, String model, double emissionsPerMile) {
        this.make = make;
        this.model = model;
        this.emissionsPerMile = emissionsPerMile;
        streetLegal = "";
    }

    public String getMake() {
        return make;
    }

    public void setMake(String make) {
        this.make = make;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public double getEmissionsPerMile() {
        return emissionsPerMile;
    }

    public void setEmissionsPerMile(double emissionsPerMile) {
        this.emissionsPerMile = emissionsPerMile;
    }

    public Person getOwner() {
        return owner;
    }

    public void setOwner(Person owner) {
        this.owner = owner;
    }

    public String getStreetLegal() {
        return streetLegal;
    }

    public void setStreetLegal(String streetLegal) {
        this.streetLegal = streetLegal;
    }

    /**
     * autogenerated equaos
     * @param o
     * @return
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Vehicle vehicle = (Vehicle) o;
        return Double.compare(vehicle.emissionsPerMile, emissionsPerMile) == 0 &&
                make.equals(vehicle.make) &&
                model.equals(vehicle.model) &&
                owner.equals(vehicle.owner);
    }

    /**
     * self created toString
     * @return
     */
    @Override
    public String toString() {
        return "This vehicle has model " + model + " and make: " + make + " it is " + streetLegal;
    }

    public void checkEmissionsData(double miles, double emissions) {
        double legalVal = miles/emissions;
        if(legalVal < 0.2){
            setStreetLegal("not street legal");
        } else{
            setStreetLegal("street legal");

        }
    }
}
